(()=>{
const $=(s,r=document)=>r.querySelector(s);
const nav=$('.tabs');
if(!nav)return;
nav.innerHTML=`
<button class="tab active" data-tab="summary">01 Summary</button><button class="tab" data-tab="market">02 Market</button><button class="tab" data-tab="avatar">03 Buyer Avatar</button><button class="tab" data-tab="pricing">04 Pricing</button><button class="tab" data-tab="positioning">05 Position</button><button class="tab" data-tab="aov">06 AOV + Offers</button><button class="tab" data-tab="site">07 Site / CRO</button><button class="tab" data-tab="marketing">08 Marketing</button><button class="tab" data-tab="metaads">09 Meta Ads Audit</button><button class="tab" data-tab="usa">10 USA + Bold</button><button class="tab" data-tab="goal">11 $10K Plan</button><button class="tab" data-tab="actions">12 Actions</button><button class="tab" data-tab="glossary">Glossary</button><button class="tab" data-tab="sources">Sources</button>`;

const summary=$('#summary .grid');
summary.insertAdjacentHTML('afterbegin',`<div class="card wide insightbox"><div class="label insightlabel">30-second read</div><div class="lang-en priority">The market is not collapsing. Amaranta’s bigger opportunity is to <span class="highlight">make premium value easier to understand, increase basket size, and aim the creative at a more specific buyer.</span></div><div class="lang-es priority">El mercado no está colapsando. La oportunidad más grande es <span class="highlight">hacer más evidente el valor premium, aumentar el valor del carrito y dirigir la creatividad a una compradora más específica.</span></div><div class="scanrow"><div class="scanitem"><span class="smallcaps">Market</span><strong class="green">Demand still exists</strong><small class="muted">Transactions rose while average online ticket fell.</small></div><div class="scanitem"><span class="smallcaps">Buyer hypothesis</span><strong class="purple">38–54 style-first woman</strong><small class="muted">High-priority hypothesis, not yet first-party proof.</small></div><div class="scanitem"><span class="smallcaps">Main lever</span><strong class="yellow">Value proof + AOV</strong><small class="muted">Not “discount the hero bag more.”</small></div></div></div>`);

$('#pricing').insertAdjacentHTML('beforebegin',`<section class="section" id="avatar"><div class="grid">
<div class="card wide insightbox"><div class="label insightlabel">Who should Amaranta speak to?</div><h2 class="lang-en">Best current messaging hypothesis: an established, style-conscious woman around <span class="red">38–54</span>.</h2><h2 class="lang-es">Mejor hipótesis actual de mensaje: una mujer establecida, consciente de su estilo, alrededor de <span class="red">38–54</span>.</h2><p class="lang-en">This is <b>not yet proven from Amaranta’s own customer data</b>. It combines Colombia ecommerce demographics, the Colombian premium/luxury buyer profile, Amaranta’s price point, and the founder’s observed customer pattern.</p><p class="lang-es">Esto <b>todavía no está probado con los datos propios de Amaranta</b>. Combina la demografía del ecommerce colombiano, el perfil premium/luxury del país, el nivel de precios de Amaranta y el patrón observado por la fundadora.</p><span class="tag med">Validate in Shopify + Meta</span></div>
<div class="card evidencebox"><div class="label evidencelabel">External evidence 1</div><div class="keynum blue">25–44</div><p class="lang-en">The U.S. International Trade Administration describes Colombia’s primary online-shopping demographic as 25–44, with middle-to-upper income shoppers especially active and Bogotá, Medellín and Cali as ecommerce strongholds.</p><p class="lang-es">La International Trade Administration de EE. UU. describe al comprador online principal en Colombia entre 25–44 años, con mayor actividad en ingresos medios-altos y fuerte presencia en Bogotá, Medellín y Cali.</p><span class="tag high">General ecommerce</span></div>
<div class="card evidencebox"><div class="label evidencelabel">External evidence 2</div><div class="keynum purple">35–45</div><p class="lang-en">Recent Colombian luxury-market reporting describes a core premium buyer around 35–45: higher purchasing power, frequent travel and an expectation of international-level brand experience.</p><p class="lang-es">Reportes recientes del mercado de lujo colombiano describen un comprador premium alrededor de 35–45: mayor poder adquisitivo, viajes frecuentes y expectativa de experiencia de marca internacional.</p><span class="tag med">Relevant proxy, not Amaranta-specific</span></div>
<div class="card avatar primary"><div class="label actionlabel">Primary creative avatar</div><h3 class="lang-en">The Established Style Buyer • 38–54</h3><h3 class="lang-es">La Compradora de Estilo Establecido • 38–54</h3><ul class="lang-en"><li>Wants distinctive and polished, not “touristy”.</li><li>Needs to see the bag with real outfits and real life.</li><li>Can pay premium when technique, finishing, time and provenance are tangible.</li><li>Likely responds better to timelessness and versatility than trend-chasing copy.</li></ul><ul class="lang-es"><li>Quiere algo especial y sofisticado, no “turístico”.</li><li>Necesita ver el bolso con outfits y vida real.</li><li>Puede pagar premium cuando técnica, acabados, tiempo y origen son tangibles.</li><li>Probablemente responde mejor a atemporalidad y versatilidad que a copy de tendencias.</li></ul></div>
<div class="card avatar secondary"><div class="label">Secondary avatar</div><h3 class="lang-en">Modern Colombian Design Buyer • 28–39</h3><h3 class="lang-es">Compradora de Diseño Colombiano Moderno • 28–39</h3><p class="lang-en">More style- and social-led. Show one artisan bag elevating simple clothing, traveling well and feeling recognizably Colombian without becoming folkloric.</p><p class="lang-es">Más guiada por estilo y redes. Mostrar una pieza artesanal elevando ropa sencilla, funcionando para viajes y sintiéndose colombiana sin volverse folclórica.</p></div>
<div class="card avatar gift"><div class="label actionlabel">High-intent occasion</div><h3 class="lang-en">Meaningful Gift Buyer</h3><h3 class="lang-es">Compradora de Regalo con Significado</h3><p class="lang-en">Amaranta already has gifting language and public reviews mentioning gifts. Build ready-to-gift packaging, delivery certainty, price tiers and “she probably does not already own this” positioning.</p><p class="lang-es">Amaranta ya tiene lenguaje de regalos y reseñas públicas que mencionan regalos. Crear empaque listo para regalar, certeza de entrega, niveles de precio y el mensaje “probablemente ella no tiene una pieza así”.</p></div>
<div class="card wide actionbox"><div class="label actionlabel">How to use this in Meta</div><p class="lang-en"><b>Message narrow, deliver broad.</b> Build creative clearly for the 38–54 woman, but do not automatically restrict delivery only to 38–54. Let creative self-select, then validate age breakdowns after enough purchases accumulate.</p><p class="lang-es"><b>Mensaje específico, entrega más amplia.</b> Crear la creatividad claramente para la mujer de 38–54, pero no limitar automáticamente la entrega solo a esa edad. Dejar que la creatividad filtre y validar edades cuando existan suficientes compras.</p></div>
<div class="card wide"><h3 class="lang-en">Messaging shift</h3><h3 class="lang-es">Cambio de mensaje</h3><table><tr><th>Less</th><th>More</th></tr><tr><td>“Unique artisanal masterpiece”</td><td>“The Colombian bag that makes a simple linen look feel finished.”</td></tr><tr><td>Generic slow-fashion language</td><td>10–12 days, technique, construction, dimensions, what fits.</td></tr><tr><td>Only Caribbean vacation imagery</td><td>Bogotá / Medellín / Cartagena: lunch, travel, dinner, everyday styling.</td></tr><tr><td>Trend language</td><td>Timeless piece + recognizable craft + wardrobe versatility.</td></tr></table></div>
</div></section>`);

$('#usa').insertAdjacentHTML('beforebegin',`<section class="section" id="metaads"><div class="grid">
<div class="card wide evidencebox"><div class="label evidencelabel">Meta research</div><h2 class="lang-en">Meta’s own testing supports building more native vertical video, not just adapting beautiful product images.</h2><h2 class="lang-es">Las propias pruebas de Meta apoyan crear más video vertical nativo, no solo adaptar fotos bonitas del producto.</h2></div>
<div class="card third evidencebox"><div class="keynum green">−34.5%</div><b class="lang-en">cost per result</b><b class="lang-es">costo por resultado</b><p class="lang-en">In Meta’s meta-analysis of 15 Reels-only split tests, 9:16 video with audio and key messages in the safe zone produced 34.5% lower cost per result than image ads.</p><p class="lang-es">En un meta-análisis de 15 pruebas de Reels, video 9:16 con audio y mensajes en zona segura produjo 34,5% menor costo por resultado que anuncios de imagen.</p></div>
<div class="card third evidencebox"><div class="keynum green">+11%</div><b class="lang-en">conversion rate</b><b class="lang-es">tasa de conversión</b><p class="lang-en">Meta reports an average 11% higher conversion rate when partner-enabled native Reels creative was added in another 15-test meta-analysis.</p><p class="lang-es">Meta reporta en promedio 11% mayor tasa de conversión al añadir creatividad nativa de Reels creada con partners en otro meta-análisis de 15 pruebas.</p></div>
<div class="card third evidencebox"><div class="keynum green">−5%</div><b class="lang-en">cost per result</b><b class="lang-es">costo por resultado</b><p class="lang-en">The same partner-enabled Reels research reported about 5% lower cost per result on average.</p><p class="lang-es">El mismo estudio reportó cerca de 5% menor costo por resultado en promedio.</p></div>
<div class="card wide callout redline"><b class="lang-en">Important:</b><b class="lang-es">Importante:</b><span class="lang-en"> these are Meta-wide experimental results, not a promise that Amaranta will get the same lift. They justify the test, not the result.</span><span class="lang-es"> son resultados experimentales globales de Meta, no una promesa para Amaranta. Justifican la prueba, no garantizan el resultado.</span></div>
<div class="card wide insightbox"><div class="label insightlabel">Public Meta audit limitation</div><p class="lang-en">Meta Ad Library is the correct public source for active ads, but I could <b>not reliably extract a complete current Amaranta advertiser-level set through automated research</b>. Therefore this report does not invent which ad is winning, spend, targeting, frequency or ROAS.</p><p class="lang-es">La Biblioteca de Anuncios de Meta es la fuente pública correcta, pero <b>no pude extraer de forma confiable el conjunto completo de anuncios actuales de Amaranta mediante investigación automatizada</b>. Por eso este informe no inventa ganador, gasto, segmentación, frecuencia ni ROAS.</p></div>
<div class="card"><div class="label actionlabel">Public-content read</div><h3 class="lang-en">Beautiful brand world; sharper selling reasons needed.</h3><h3 class="lang-es">Mundo de marca bonito; faltan razones de compra más claras.</h3><p class="lang-en">Indexed Amaranta content leans on craft, Colombia, gifting, beauty and lifestyle. Keep those assets, but add proof and use-cases that answer: why this bag, why this price, why now?</p><p class="lang-es">El contenido indexado se apoya en artesanía, Colombia, regalos, belleza y lifestyle. Mantenerlo, pero sumar prueba y usos concretos que respondan: ¿por qué este bolso, por qué este precio y por qué ahora?</p></div>
<div class="card"><div class="label actionlabel">Creator opportunity</div><h3 class="lang-en">Use real women + full outfits, not only isolated bags.</h3><h3 class="lang-es">Usar mujeres reales + outfits completos, no solo bolsos aislados.</h3><p class="lang-en">Recent indexed social content shows Amaranta inside a broader Colombian-fashion look. This is a strong model for creator/partnership content: person, outfit, context, bag as the finishing piece.</p><p class="lang-es">Contenido social reciente indexado muestra Amaranta dentro de un look más amplio de moda colombiana. Es un buen modelo para partnerships: persona, outfit, contexto y bolso como pieza final.</p></div>
<div class="card wide"><div class="label actionlabel">Creative matrix to test</div><table><tr><th>Family</th><th>Hook</th><th>Show</th><th>Belief</th></tr><tr><td><b>Premium proof</b></td><td>Why this is not a COP 250k marketplace bag</td><td>Weave, 10–12 days, finishing, artisan work</td><td>The premium is real</td></tr><tr><td><b>38–54 style demo</b></td><td>The bag that makes a simple outfit feel finished</td><td>Realistic woman, 3 outfits, movement</td><td>This fits my wardrobe</td></tr><tr><td><b>Utility</b></td><td>What actually fits in the Mochilón?</td><td>Real everyday contents</td><td>Beautiful + usable</td></tr><tr><td><b>Colombia, refined</b></td><td>Colombian craft for everyday city life</td><td>Urban styling + craft close-ups</td><td>Heritage can feel sophisticated</td></tr><tr><td><b>Ready now</b></td><td>Handmade does not always mean waiting</td><td>Specific in-stock pieces</td><td>I can buy now</td></tr><tr><td><b>Gift</b></td><td>A gift she is unlikely to already own</td><td>Packaging + recipient + delivery certainty</td><td>Distinctive safe gift</td></tr></table></div>
<div class="card actionbox"><div class="label actionlabel">Account testing direction</div><ul class="lang-en"><li>Keep delivery relatively broad and let creative filter the audience.</li><li>Do not fragment small budgets into many age/interest ad sets.</li><li>Test 3–5 genuinely different concepts, not five cosmetic variations.</li><li>Send Ready-to-Ship ads to ready inventory.</li><li>Keep ad → landing-page message consistent.</li></ul><ul class="lang-es"><li>Mantener entrega relativamente amplia y dejar que la creatividad filtre.</li><li>No fragmentar presupuestos pequeños en demasiados conjuntos por edad/intereses.</li><li>Probar 3–5 conceptos realmente distintos, no cinco variaciones cosméticas.</li><li>Enviar Ready-to-Ship a inventario listo.</li><li>Mantener coherencia anuncio → landing.</li></ul></div>
<div class="card actionbox"><div class="label actionlabel">Data needed for a real account audit</div><p class="lang-en">Export 30–90 days by campaign, ad set and ad:</p><p class="lang-es">Exportar 30–90 días por campaña, conjunto y anuncio:</p><ul><li>Spend, purchases, purchase value</li><li>CPM, outbound CTR, CPC</li><li>LPV, ATC, checkout, purchases</li><li>CPA and ROAS</li><li>Frequency and creative age</li><li>Age + placement breakdown</li><li>New vs returning customer revenue</li></ul></div>
</div></section>`);

$('#sources').insertAdjacentHTML('beforebegin',`<section class="section" id="glossary"><div class="grid"><div class="card wide"><h2 class="lang-en">Ecommerce terms in plain language</h2><h2 class="lang-es">Términos de ecommerce en lenguaje simple</h2><p class="lang-en muted">Tap any dotted-underlined term anywhere in the dashboard. This glossary is also here as a reference.</p><p class="lang-es muted">Toca cualquier término subrayado con puntos. Este glosario también queda como referencia.</p><div class="gloss" id="glossGrid"></div></div></div></section>`);

const sources=$('#sources .card.wide');
if(sources)sources.insertAdjacentHTML('beforeend',`<a class="source" href="https://www.trade.gov/country-commercial-guides/colombia-ecommerce" target="_blank">U.S. International Trade Administration — Colombia ecommerce demographics</a><a class="source" href="https://www.portafolio.co/tendencias/lujo/medellin-concentra-el-60-de-ventas-de-lujo-en-colombia-y-lidera-expansion-del-segmento-premium-493374" target="_blank">Portafolio — Colombia premium/luxury buyer profile, 2026</a><a class="source" href="https://www.facebook.com/business/ads/facebook-instagram-reels-ads" target="_blank">Meta for Business — Reels creative research</a><a class="source" href="https://www.facebook.com/ads/library/" target="_blank">Meta Ad Library — active-ad research source</a><p class="source-note">Meta audit limitation: a complete current advertiser-level Amaranta ad set was not reliably retrievable through automated public research. No ad-level winner, spend, targeting or ROAS claim is invented.</p>`);

const TERMS={
AOV:{en:'Average Order Value: the average amount a customer spends in one order. Example: COP 30M revenue from 60 orders = COP 500k AOV.',es:'Valor Promedio del Pedido: cuánto gasta en promedio una clienta por pedido. Ejemplo: COP 30M en 60 pedidos = COP 500k de AOV.'},
CVR:{en:'Conversion Rate: the percentage of store visitors who buy. 2 purchases from 100 sessions = 2% CVR.',es:'Tasa de Conversión: porcentaje de visitantes que compran. 2 compras de 100 sesiones = 2% de CVR.'},
CRO:{en:'Conversion Rate Optimization: improving the store or funnel so a higher percentage of visitors buy.',es:'Optimización de Conversión: mejorar la tienda o funnel para que un mayor porcentaje de visitantes compre.'},
CAC:{en:'Customer Acquisition Cost: average marketing cost to acquire one new customer.',es:'Costo de Adquisición de Cliente: costo promedio de marketing para conseguir un cliente nuevo.'},
CPA:{en:'Cost Per Acquisition / Purchase: ad spend divided by purchases attributed to the ads.',es:'Costo por Adquisición / Compra: gasto publicitario dividido entre las compras atribuidas a anuncios.'},
ROAS:{en:'Return on Ad Spend: attributed revenue divided by ad spend. ROAS 3 means COP 3 in attributed sales per COP 1 spent.',es:'Retorno sobre Gasto Publicitario: ventas atribuidas divididas entre gasto. ROAS 3 = COP 3 de ventas por cada COP 1 gastado.'},
CPM:{en:'Cost per 1,000 impressions: average cost to show ads 1,000 times.',es:'Costo por 1.000 impresiones: costo promedio de mostrar anuncios 1.000 veces.'},
CTR:{en:'Click-Through Rate: percentage of impressions that produce a click. Outbound CTR counts clicks leaving Meta for the website.',es:'Tasa de Clics: porcentaje de impresiones que generan clic. Outbound CTR cuenta clics que salen de Meta hacia la web.'},
CPC:{en:'Cost Per Click: average ad cost for each click.',es:'Costo por Clic: costo publicitario promedio por cada clic.'},
LPV:{en:'Landing Page View: someone clicked the ad and actually loaded the landing page.',es:'Vista de Landing Page: alguien hizo clic y realmente cargó la página de destino.'},
ATC:{en:'Add to Cart: a shopper added a product to the cart.',es:'Agregar al Carrito: una persona agregó un producto al carrito.'},
PDP:{en:'Product Detail Page: the product page with photos, price, description, proof, options and Add to Cart.',es:'Página de Producto: página con fotos, precio, descripción, prueba, opciones y Agregar al Carrito.'},
COGS:{en:'Cost of Goods Sold: direct product cost of what was sold, before marketing and many overhead expenses.',es:'Costo de Productos Vendidos: costo directo del producto vendido antes de marketing y muchos gastos generales.'},
SKU:{en:'Stock Keeping Unit: unique inventory record for a specific product or variant.',es:'Unidad de Inventario: registro único de inventario para un producto o variante.'},
UGC:{en:'User-Generated Content: customer- or creator-style content that feels native to social media.',es:'Contenido Generado por Usuarios/Creadores: contenido que se siente nativo de redes sociales.'},
LTV:{en:'Lifetime Value: total value a customer generates across all purchases over time.',es:'Valor de Vida del Cliente: valor total que genera una clienta sumando todas sus compras.'},
FREQUENCY:{en:'Frequency: average number of times each person saw an ad. High/rising frequency can sometimes signal creative fatigue.',es:'Frecuencia: número promedio de veces que cada persona vio un anuncio. Una frecuencia alta o creciente puede indicar fatiga creativa.'},
RETARGETING:{en:'Retargeting: advertising again to people who already visited, engaged or added to cart but did not buy.',es:'Retargeting: volver a anunciar a personas que ya visitaron, interactuaron o agregaron al carrito sin comprar.'}
};

document.body.insertAdjacentHTML('beforeend',`<div class="tooltip" id="termTip" role="dialog" aria-live="polite"><button class="tooltip-close" id="termClose">×</button><div class="tooltip-title" id="termTitle"></div><div class="tooltip-body" id="termBody"></div></div>`);
const lang=()=>document.body.classList.contains('es')?'es':'en';
function buildGloss(){const g=$('#glossGrid');if(!g)return;g.innerHTML='';Object.entries(TERMS).forEach(([k,v])=>{const d=document.createElement('div');d.innerHTML=`<b>${k}</b><small>${v[lang()]}</small>`;g.appendChild(d)})}
function showTerm(k){const key=k.toUpperCase(),d=TERMS[key];if(!d)return;$('#termTitle').textContent=key;$('#termBody').textContent=d[lang()];$('#termTip').classList.add('show')}
function linkTerms(){const keys=Object.keys(TERMS).sort((a,b)=>b.length-a.length),re=new RegExp('\\b('+keys.join('|')+')\\b','gi'),root=$('main'),w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{if(!n.parentElement||n.parentElement.closest('script,style,a,.term'))return;const txt=n.nodeValue;if(!re.test(txt)){re.lastIndex=0;return}re.lastIndex=0;const f=document.createDocumentFragment();let last=0;txt.replace(re,(m,_,off)=>{f.append(document.createTextNode(txt.slice(last,off)));const s=document.createElement('span');s.className='term';s.dataset.key=m.toUpperCase();s.textContent=m;f.append(s);last=off+m.length});f.append(document.createTextNode(txt.slice(last)));n.replaceWith(f);re.lastIndex=0})}
window.toggleLang=function(){document.body.classList.toggle('es');$('#langBtn').textContent=document.body.classList.contains('es')?'ES / EN':'EN / ES';buildGloss();$('#termTip').classList.remove('show')};
nav.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{nav.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));const s=document.getElementById(t.dataset.tab);if(s)s.classList.add('active');window.scrollTo({top:nav.offsetTop-55,behavior:'smooth'})}));
document.addEventListener('click',e=>{const t=e.target.closest('.term');if(t){showTerm(t.dataset.key);return}if(e.target.id==='termClose')$('#termTip').classList.remove('show')});
document.addEventListener('mouseover',e=>{const t=e.target.closest('.term');if(t&&matchMedia('(hover:hover)').matches)showTerm(t.dataset.key)});document.addEventListener('keydown',e=>{if(e.key==='Escape')$('#termTip').classList.remove('show')});
linkTerms();buildGloss();
})();