(()=>{
const overlay=document.getElementById('overlay'),content=document.getElementById('sheetContent'),toast=document.getElementById('toast'),sheetClose=document.getElementById('sheetClose'),sticky=document.getElementById('stickyJoin'),stickyBtn=document.getElementById('stickyJoinBtn');
let s={email:localStorage.getItem('moki_email')||'',q1:'',q2:'',remaining:300,timer:null};
const q1=['Instagram','TikTok','YouTube','Reddit','X','Other'],q2=['Outside','People','Create','Move','Read','Explore','Calm'];
const quests={Outside:'Step outside for five minutes. No headphones. Notice three things you normally walk past.',People:'Send a real voice note to someone you actually care about. No scrolling after.',Create:'Make something for five minutes — sketch, write, play, build.',Move:'Walk for five minutes without opening a feed.',Read:'Read five pages with your phone face down.',Explore:'Walk somewhere nearby you usually ignore. Find one detail you have never noticed.',Calm:'Sit somewhere for five minutes without a feed. Let yourself be bored.'};
const questImages={Outside:'../assets-v5/quest-sunrise.webp',People:'../assets-v3/people.webp',Create:'../assets-v5/scroll-cafe.webp',Move:'../assets-v5/trail-run.webp',Read:'../assets-v5/scroll-cafe.webp',Explore:'../assets-v5/lake.webp',Calm:'../assets-v3/final.webp'};
function toastIt(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
function open(h){content.innerHTML=h;overlay.classList.add('open');document.body.style.overflow='hidden'}
function close(){overlay.classList.remove('open');document.body.style.overflow='';clearInterval(s.timer)}
sheetClose.onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};
function prog(n){return `<div class="progress"><i class="${n>=1?'on':''}"></i><i class="${n>=2?'on':''}"></i></div>`}
function ask1(){open(`${prog(1)}<h3>What pulls you in most?</h3><p>Pick the one that steals the most accidental time.</p><div class="options">${q1.map(x=>`<button class="opt" data-v="${x}">${x}</button>`).join('')}</div><button class="primary" id="n1" disabled>Continue</button>`);document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{document.querySelectorAll('.opt').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');s.q1=b.dataset.v;document.getElementById('n1').disabled=false});document.getElementById('n1').onclick=ask2}
function ask2(){open(`${prog(2)}<h3>What do you want more of instead?</h3><p>This chooses your first Side Quest.</p><div class="options">${q2.map(x=>`<button class="opt" data-v="${x}">${x}</button>`).join('')}</div><button class="primary" id="n2" disabled>Give me a quest</button>`);document.querySelectorAll('.opt').forEach(b=>b.onclick=()=>{document.querySelectorAll('.opt').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');s.q2=b.dataset.v;document.getElementById('n2').disabled=false});document.getElementById('n2').onclick=showQuest}
function showQuest(){let q=quests[s.q2]||quests.Outside,img=questImages[s.q2]||questImages.Outside;open(`<div class="questModal"><img src="${img}" alt="MOKI Side Quest"><div class="qmCopy"><div class="kicker lime">YOUR FIRST SIDE QUEST</div><h4>${s.q2||'Outside'}</h4><p>${q}</p></div></div><p>MOKI doesn’t need more of your screen time. Give him five minutes of your real life.</p><button class="primary" id="start" style="width:100%">Start 5 minutes</button><button id="preview" style="width:100%;height:42px;border:0;background:transparent;color:#77847c">Preview completion</button>`);document.getElementById('start').onclick=start;document.getElementById('preview').onclick=complete}
function start(){s.remaining=300;renderTimer();s.timer=setInterval(()=>{s.remaining--;tick();if(s.remaining<=0){clearInterval(s.timer);complete()}},1000)}
function renderTimer(){let img=questImages[s.q2]||questImages.Outside;open(`<div class="timer"><div class="timerScene"><img src="${img}" alt="Your Side Quest"></div><p>Put the phone down. MOKI will be here.</p><div class="timerNum" id="time">05:00</div></div><button id="early" style="width:100%;height:44px;border:0;background:transparent;color:#77847c">End early</button>`);document.getElementById('early').onclick=complete}
function tick(){let m=Math.floor(s.remaining/60),x=s.remaining%60,e=document.getElementById('time');if(e)e.textContent=String(m).padStart(2,'0')+':'+String(x).padStart(2,'0')}
function complete(){clearInterval(s.timer);open(`<h3>You just traded 5 minutes of scrolling for your actual life.</h3><p>How did it feel?</p><div class="reflect"><button data-r="better">Better than scrolling</button><button data-r="same">About the same</button><button data-r="no">Not for me</button></div>`);document.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>finish(b.dataset.r))}
function finish(r){localStorage.setItem('moki_demo',JSON.stringify({email:s.email,q1:s.q1,q2:s.q2,result:r,completedAt:Date.now()}));if(r==='better')open(`<div class="kicker">YOU MADE MOKI REAL</div><h3>Want to be in the first beta wave?</h3><p>You tried the idea before the app exists.</p><div class="founding"><b>MOKI Founding Pass</b><div class="price">$9</div><p>Priority beta access · First month of MOKI+ free · Founding status</p><button class="primary" id="found" style="width:100%">Founding Pass — coming next</button></div>`);else open(`<h3>Thanks for trying it.</h3><p>That answer is useful too. You’re still on the early list.</p><button class="primary" id="done" style="width:100%">Done</button>`);if(document.getElementById('found'))document.getElementById('found').onclick=()=>toastIt('Public demo: payments are intentionally disabled');if(document.getElementById('done'))document.getElementById('done').onclick=close}
function join(email){s.email=email;localStorage.setItem('moki_email',email);sticky.classList.remove('show');ask1()}
document.querySelectorAll('.joinForm').forEach(f=>f.onsubmit=e=>{e.preventDefault();let email=f.querySelector('input').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return toastIt('Enter a valid email');join(email)});
document.querySelectorAll('.tryQuest').forEach(b=>b.onclick=()=>s.email?ask1():document.querySelector('.heroJoin input').focus());
stickyBtn.onclick=()=>{const el=document.querySelector('.heroJoin input');el.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>el.focus(),450)};
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));
const hero=document.querySelector('.heroSection');const stickyIO=new IntersectionObserver(es=>{const heroVisible=es[0].isIntersecting;if(window.innerWidth<=720&&!heroVisible&&!s.email)sticky.classList.add('show');else sticky.classList.remove('show')},{threshold:.04});stickyIO.observe(hero);
})();
