'use strict';
(()=>{
const features=window.CATALOG_FEATURES,sources=window.CATALOG_SOURCES,categories=window.CATALOG_CATEGORIES;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₪'+new Intl.NumberFormat('he-IL',{maximumFractionDigits:0}).format(n);
const labels={first:'כדאי לבדוק קודם',test:'ניסוי ממוקד',later:'להמשך'};
const assets={pack:'https://tigerbrandsglobal.com/cdn/shop/t/9/assets/tigera-novahair-pack-exact.webp?v=106415958521108498121786640207',gloss:'https://tigerbrandsglobal.com/cdn/shop/t/9/assets/tigera-hair-gloss-exact.webp?v=171914226990193282481786640209',hero:'https://tigerbrandsglobal.com/cdn/shop/t/9/assets/tbg-home-hero-novahair-editorial-v5.webp?v=21521982433243453061788226964'};
const photo=(key='pack',height=85)=>`<div class="photo-box" style="height:${height}px"><span class="fallback" aria-hidden="true">NOVAHAIR<br><small>תצוגת מוצר</small></span><img src="${assets[key]}" width="280" height="280" loading="lazy" decoding="async" alt="${key==='gloss'?'ספריי גלוס':key==='hero'?'תמונת המותג':'מוצרי NovaHair'} — נכס מהאתר הציבורי"></div>`;
const btn=(label,act,value='',extra='')=>`<button type="button" data-action="${act}" data-value="${value}" ${extra}>${label}</button>`;
const note=t=>`<span class="footnote">${t}</span>`;
const wrap=(body,cls='')=>`<div class="mini ${cls}">${body}</div>`;
const sample=()=>note('נתוני הדגמה בלבד · לא מחובר לחנות');
const qty=(n=1,act='qty',v='')=>`<span class="qty">${btn('−',act,v?`${v}:-1`:'-1','aria-label="הפחתת כמות"')}<b data-q>${n}</b>${btn('+',act,v?`${v}:1`:'1','aria-label="הגדלת כמות"')}</span>`;
const swatches=(act='shade')=>`<div class="swatches">${[['שחור','#24251f'],['חום כהה','#514132'],['חום בהיר','#927755'],['אדום','#8b3336'],['סגול','#64406d']].map(([n,c],i)=>btn('',act,n,`style="--sw:${c}" class="${i===0?'on':''}" aria-label="${n}" aria-pressed="${i===0}"`)).join('')}</div>`;
const lines=()=>'<div class="page-lines"><i></i><i></i><i></i></div>';
const browser=(body,cls='')=>`<div class="mock-browser"><div class="browser-bar"><i></i><i></i><i></i><span>DESIGN PREVIEW · NOT A LIVE STORE</span></div><div class="page-content ${cls}">${body}</div></div>`;
const renders={
 drawer:()=>wrap(`<div class="row"><h4>סל הקניות שלך</h4><span class="pill">דמו</span></div><div class="item"><div style="width:70px">${photo()}</div><div class="desc"><b>ערכת NovaHair</b><div class="micro">חום כהה · ערכת אביזרים</div>${qty()}</div></div><hr class="hr"><div class="row"><span>סך הכול</span><b data-total>₪129</b></div>${btn('להמשך לתשלום ←','checkout','','class="dark full" style="margin-top:10px"')}${note('כפתור הדגמה בלבד — אין רכישה')}`),
 shipping:()=>wrap(`<span class="pill">משלוח</span><h4 style="margin-top:12px" data-shiptext>עוד ₪29 למשלוח חינם</h4><div class="progress"><i data-fill style="--w:85.4%"></i></div><div class="row"><span>סל הדגמה</span><b data-amount>₪170</b></div><input type="range" data-input="shipping" aria-label="סכום סל לדוגמה" min="30" max="300" value="170">${note('גרור כדי לשנות את הסכום · סף דוגמה: ₪199')}`),
 bundles:()=>wrap(`<h4>בחרי את הערכה שלך</h4><div class="stack">${[[1,129,'התחלה'],[2,219,'שגרה'],[3,299,'ערכה מורחבת']].map(([n,p,t],i)=>`<button class="option ${i===1?'on':''}" data-action="bundle" data-value="${p}" aria-pressed="${i===1}"><span><b>${t} · ${n} יח׳</b><small>${money(p/n)} ליחידה</small></span><b>${money(p)}</b></button>`).join('')}</div><div class="row" style="margin-top:10px"><small>הבחירה שלך</small><b data-bundleprice>₪219</b></div>`),
 mix:()=>wrap(`<div class="row"><h4>הרכיבי 3 יחידות</h4><span class="pill" data-mixcount>2 / 3</span></div>${[['שחור','#22251f',1],['חום כהה','#66503b',1],['חום בהיר','#a28a63',0]].map(([n,c,v],i)=>`<div class="mixrow"><span><i class="dot" style="--sw:${c}"></i>${n}</span>${qty(v,'mix',String(i))}</div>`).join('')}${btn('בחרי עוד יחידה','mixdone','','class="dark full" data-mixdone disabled')}${note('חיבור ל־SKU, מלאי והזמנה נדרש בנפרד')}`),
 bump:()=>wrap(`<h4>להשלים את שגרת הטיפוח?</h4><div class="item"><div style="width:65px">${photo('gloss')}</div><div class="desc"><b>ספריי גלוס לשיער</b><p>הצעה משלימה באותה הזמנה.</p><label><input type="checkbox" data-input="bump"> להוסיף ב־₪29</label></div></div><hr class="hr"><div class="row"><span>סכום הדוגמה</span><b data-bumptotal>₪219</b></div>`),
 sticky:()=>`<div class="mini-scroll" tabindex="0" aria-label="אזור גלילה המדגים כפתור צף"><div class="scroll-content"><b>גלול בתוך החלון ↓</b><h4>כל מה שחשוב לדעת<br>לפני שבוחרים.</h4>${lines()}<p>הכפתור נשאר זמין בזמן שקוראים.</p><div style="height:90px"></div><p>המידע ממשיך כאן.</p></div><div class="sticky-preview"><span><b>ערכת NovaHair</b><br><small>₪219 · דוגמה</small></span>${btn('בחירת הערכה','notify','הכפתור יחובר לטופס המוצר הקיים.','class="dark"')}</div></div>${note('הכפתור דביק בתוך חלון ההדגמה בלבד')}`,
 shades:()=>wrap(`<div class="row"><div style="width:43%">${photo('pack',125)}</div><div class="desc"><small>הבחירה שלך</small><h4 data-shadelabel>שחור</h4><p>שם גוון ברור לצד הבחירה.</p></div></div>${swatches()}${note('תמונת המוצר אינה הדמיה של תוצאת גוון')}`),
 gallery:()=>wrap(`<div class="photo-box gallery-main"><span class="fallback">NOVAHAIR</span><img data-galleryimg src="${assets.pack}" loading="lazy" width="280" height="200" alt="תמונת קטלוג מהחנות"><span class="gallery-caption" data-gallerycaption>מוצר / 01</span></div><div class="thumbs">${[['pack','מוצר'],['hero','מותג'],['gloss','גלוס']].map(([key,t],i)=>btn(t,'gallery',key,`aria-label="תצוגת ${t}" class="${i===0?'on':''}"`)).join('')}</div>${note('בחר תמונה; מקור PhotoSwipe מיועד גם להגדלה')}`),
 beforeafter:()=>wrap(`<div class="comparison-visual"><div class="after"></div><span class="cap before">לפני</span><span class="cap aftercap">אחרי</span><div class="divider"></div></div><input aria-label="מחיצת השוואה" type="range" min="0" max="100" value="50" data-input="beforeafter">${note('טקסטורה סכמטית בלבד — לא תוצאת שימוש')}`),
 ugc:()=>wrap(`<h4>לראות איך זה עובד</h4><div class="video-row">${['הכנה','יישום','שאלות'].map((t,i)=>`<div class="video-tile">${btn('▶','video',t,`aria-label="בחירת קליפ ${t}"`)}<b>${t}</b></div>`).join('')}</div><small data-videostate>הדמיית ממשק · ללא סרטוני מקור</small>`),
 reviews:()=>wrap(`<div class="row"><h4>חוויות מהשגרה</h4><span class="stars">★★★★★</span></div><div class="row" style="justify-content:start">${['גוון','שימוש','משלוח'].map((t,i)=>btn(t,'review',t,`class="${i===0?'on':''}"`)).join('')}</div><div class="chatline" style="margin-top:14px" data-review>כאן תוצג ביקורת אמיתית ומאושרת בנושא בחירת הגוון.</div><small>מקום שמור למקור הביקורת ולאימות רכישה</small>${note('תצוגת דוגמה. הכוכבים אינם דירוג החנות.')}`),
 faq:()=>wrap(`<h4>רגע לפני שמזמינים</h4>${[['אפשר לשלב גוונים?','ניתן להציג כאן תשובה המתאימה להרכב החבילה המאושר.'],['מה מגיע בערכה?','פירוט יישאב מהמוצר ומהחבילה שנבחרו — לא מטקסט קשיח.'],['איך משתמשים?','קוראים ופועלים לפי הוראות היצרן והאזהרות שעל האריזה.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}`),
 compare:()=>wrap(`<h4>מה כלול בכל אפשרות?</h4><table class="compare-table"><thead><tr><th>הרכיב</th><th>ערכה</th><th>יחידה</th></tr></thead><tbody><tr><td>בחירת גוון</td><td>✓</td><td>✓</td></tr><tr><td>אביזרים</td><td>כלולים*</td><td>בנפרד</td></tr><tr><td>הרכב הזמנה</td><td>מרוכז</td><td>פריט אחד</td></tr></tbody></table>${note('*השוואה לדוגמה בלבד; להחליף בנתוני ההצעה.')}`),
 delivery:()=>wrap(`<span class="pill">שקיפות לפני קנייה</span><h4 style="margin-top:10px">מה קורה אחרי ההזמנה?</h4><div class="stepper"><span><i>1</i>הזמנה</span><span><i>2</i>הכנה</span><span><i>3</i>הובלה</span><span><i>4</i>איסוף</span></div>${btn('מה משפיע על הזמן?','delivery','','class="full"')}<p data-delivery hidden>סוג המשלוח, מלאי, זמן טיפול, יעד וחגים. טווח אמיתי יוצג רק מחישוב נתוני ספק.</p>${note('דמו מסלול — אין כאן הערכת זמן אמיתית')}`),
 quickview:()=>wrap(`<div data-quickclosed class="row"><div style="width:90px">${photo('gloss',140)}</div><div><h4>ספריי גלוס</h4><p>לצד המוצר הראשי</p>${btn('מבט מהיר ↗','quick')}</div></div><div data-quickopen hidden><div class="row"><h4>ספריי גלוס</h4>${btn('×','quick','','aria-label="סגירת מבט מהיר"')}</div><p>כאן יוצגו תיאור, מחיר וזמינות מהמוצר האמיתי.</p>${photo('gloss',90)}${btn('בחירת מוצר — דמו','notify','אין הוספה לסל. זוהי הדגמת מבט מהיר.','class="dark full"')}</div>`),
 pdp:()=>browser(`<div class="eyebrow">NOVAHAIR / PRODUCT PAGE</div><div class="page-split"><div><h4>הצבע שלך.<br>בקצב שלך.</h4><p class="micro">הצעה ברורה. גוון. פעולה אחת.</p><b>₪219 <small>לדוגמה</small></b></div>${photo('pack',130)}</div><div style="margin:10px 0">${swatches()}</div>${btn('לבחירת הערכה','notify','זהו קונספט עמוד, לא חנות פעילה.','class="dark full" style="padding:8px;background:#172e26;color:white;border-radius:5px"')}`),
 advertorial:()=>browser(`<div class="eyebrow">TIGER EDIT · תוכן מסחרי לדוגמה</div><h4>לפני הצביעה הבאה:<br>7 דברים שכדאי לבדוק.</h4>${['מה באמת מגיע בערכה?','איך בוחרים גוון?','מה צריך להכין מראש?'].map((t,i)=>`<div class="reason"><b>${i+1}</b><span>${t}</span></div>`).join('')}${btn('לגלות את האפשרויות ←','notify','כאן יחובר מעבר מדיד לעמוד ההצעה.','style="margin-top:10px;background:#172e26;color:white;padding:9px;border-radius:4px"')}`,'editorial'),
 landingcompare:()=>browser(`<div class="eyebrow">מדריך בחירה · הדגמה</div><h4>איזו שגרה מתאימה לך?</h4><div class="metric-grid"><div><small>אני מעדיפה</small><h5>ערכה מסודרת</h5><p class="micro">בחירה מרוכזת</p>${btn('בחירה','choice','ערכה מסודרת')}</div><div><small>אני מעדיפה</small><h5>מוצר בודד</h5><p class="micro">בחירה נקודתית</p>${btn('בחירה','choice','מוצר בודד')}</div></div><p class="micro" data-choice>שתי אפשרויות. תנאים שקופים.</p>`),
 quiz:()=>wrap(`<span class="pill" data-quizstep>שאלה 1 מתוך 2</span><h4 style="margin-top:15px" data-quiztitle>במה תרצי עזרה?</h4><div class="stack" data-quizoptions>${['בחירת גוון','הבנת הערכה'].map(t=>btn(t,'quiz',t,'class="option"')).join('')}</div>${note('דמו כללים בלבד, לא אבחון או התאמה מקצועית')}`),
 popup:()=>`<div class="veil"><div class="mini popup"><button class="cross" data-action="popupclose" aria-label="הסתרת דמו פופאפ">×</button><div class="mini-mark">↗</div><h4>לפני שבוחרים גוון,<br>עושים קצת סדר.</h4><p>מדריך קצר למה שכדאי לבדוק.</p><form data-demoform><input type="email" placeholder="האימייל שלך" aria-label="אימייל להדגמה בלבד" required><label class="micro"><input type="checkbox" required> מסכימה לקבל את המדריך</label><button class="dark full" style="margin-top:7px">לקבלת המדריך — דמו</button></form><small>לא נשמרת ולא נשלחת כתובת</small></div><button data-action="popupreset" hidden class="quiet full">להציג את הדמו מחדש</button></div>`,
 concierge:()=>wrap(`<div class="row"><h4>איך אפשר לעזור?</h4><span class="pill">תפריט דמו</span></div><div class="chatline" data-chat>בחרי נושא ונציג את המידע הרלוונטי.</div><div class="chat-options">${['גוונים','משלוח','שימוש'].map(t=>btn(t,'chat',t)).join('')}</div>${note('לא AI מחובר, לא שיחה עם נציג ולא WhatsApp')}`),
 imagespeed:()=>wrap(`<div class="dash-label">IMAGE BUDGET / סימולציה</div><h4>אותה תצוגה, משקל שונה</h4><div class="row"><span>רוחב תמונה לדוגמה</span><b data-imgwidth>1600px</b></div><input type="range" min="400" max="2400" step="200" value="1600" data-input="imagespeed" aria-label="רוחב תמונה בסימולציה"><div class="metric-grid"><div><small>משקל משוער לדוגמה</small><b data-imgkb>480 KB</b></div><div><small>התאמה למסך</small><b style="font-size:17px">srcset</b></div></div>${note('מודל דוגמה: 0.3 KB לכל פיקסל רוחב; לא מדידה')}`,'dashboard'),
 videoload:()=>wrap(`<div class="dash-label">CLICK-TO-LOAD / סימולציה</div><h4>לפני הלחיצה על Play</h4><span class="bigvalue" data-videobytes>12 MB</span><p>3 סרטונים לעומת 3 תמונות פתיחה</p><label><input type="checkbox" data-input="videoload"> טעינה לפי דרישה</label><div class="progress"><i data-fill style="--w:100%"></i></div>${note('דוגמה: 4 MB לסרטון או 80 KB לתמונת פתיחה')}`,'dashboard'),
 cls:()=>wrap(`<h4>הכפתור שלא בורח</h4><div class="sim-box"><div class="sim-picture" data-clsimg hidden>מקום לתמונה</div><div class="sim-button">בחירת הערכה</div>${lines()}</div><div class="row" style="margin-top:9px">${btn('טעינת תמונה','cls')}<label class="micro"><input type="checkbox" data-input="clsreserve"> שמירת מקום מראש</label></div>${note('המחשה ויזואלית בלבד, ללא ציון CLS')}`),
 scripts:()=>wrap(`<div class="dash-label">LOADING ORDER / הדגמה</div><h4>קודם החנות. אחר כך התוספות.</h4><div data-scripts>${[['תוכן ראשי',95],['קנייה',85],['וידאו',80],['צ׳אט',70]].map(([t,w])=>`<div class="scriptline"><span>${t}</span><i style="--w:${w}%"></i></div>`).join('')}</div>${btn('להדגים טעינה מדורגת','scripts','','class="full"')}${note('לא דוחה בפועל סקריפטים באתר שלך')}`,'dashboard'),
 quality:()=>wrap(`<div class="dash-label">RELEASE CHECKLIST / נתוני דוגמה</div><h4>לפני שהקוד עולה</h4>${[['Liquid / Theme Check','לבדיקה'],['מקלדת + מובייל','לבדיקה'],['גוונים → סל → קופה','לבדיקה'],['תקציב ביצועים','לבדיקה']].map(([t,s])=>`<div class="checkrow"><span>${t}</span><em class="warn">${s}</em></div>`).join('')}${btn('הדגמת דוח','quality','','class="full" style="margin-top:8px"')}`,'dashboard'),
 emailcart:()=>`<div class="mini email"><div class="wordmark">NOVAHAIR</div><h4>הבחירה שלך מחכה לך.</h4><p>עוד לא החלטת? אפשר לחזור לערכה ולבדוק שוב את הפרטים.</p><div class="item"><div style="width:60px">${photo('pack',70)}</div><span>הערכה שבחרת<br><small>פרטי הזמנה להמחשה</small></span></div>${btn('לחזרה לקופה ←','notify','במערכת האמיתית יופיע קישור שחזור זכאי; כאן לא נשלח דבר.','class="dark full" style="margin-top:10px"')}<div class="email-footer">העדפות דיוור · הסרה · תצוגת דוגמה</div></div>`,
 emailafter:()=>`<div class="mini email"><div class="wordmark">NOVAHAIR / YOUR ROUTINE</div><h4>רגע לפני השימוש הראשון.</h4><p>כל ההנחיות החשובות במקום אחד.</p><div class="stack"><div class="chatline">01 · קוראים את הוראות האריזה</div><div class="chatline">02 · מכינים את סביבת העבודה</div></div>${btn('למדריך השימוש','notify','כאן יחובר מדריך מאושר, לא טקסט שנוצר ללא בדיקה.','class="dark full"')}<div class="email-footer">הדגמה · לא נשלח מייל ולא שונה סטטוס הזמנה</div></div>`,
 flow:()=>`<div class="flow">${[['אירוע: קופה שננטשה','בדיקת מקור האירוע והסכמה'],['המתנה: שעה','תזמון לדוגמה בלבד'],['האם כבר נרכשה ההזמנה?','בדיקה מחדש לפני כל שליחה'],['שליחה רק אם זכאית','ספק משלוח + suppression list']].map(([t,v],i)=>`${i?'<div class="node arrow">↓</div>':''}<button class="node" data-action="node" data-value="${v}">${t}</button>`).join('')}</div><span class="footnote" data-nodetext>לחץ על שלב; התרשים אינו מריץ אוטומציה.</span>`,
 abtest:()=>wrap(`<div class="row"><span class="dash-label">EXPERIMENT PREVIEW</span><span class="pill">לא פעיל</span></div><div class="row" style="justify-content:start;margin:10px 0">${btn('גרסה A','ab','A','class="on"')}${btn('גרסה B','ab','B')}</div><div class="chatline"><h4 data-abtitle>הצבע שלך, בבית.</h4><p data-abcopy>הצעה ממוקדת מוצר.</p></div><small>המדד הראשי: רכישה · ללא נתוני ניסוי</small>`,'dashboard'),
 funnel:()=>wrap(`<div class="row"><h4>מהביקור ועד הרכישה</h4><select aria-label="ערוץ בסימולציה" data-input="funnel" style="width:85px"><option value="social">Social</option><option value="organic">Organic</option></select></div><div data-funnel>${[[1000,'ביקורים',100],[120,'סל',65],[60,'קופה',43],[24,'רכישה',25]].map(([n,t,w])=>`<div class="funnel-row" style="--w:${w}%"><span>${t}</span><b>${n}</b></div>`).join('')}</div>${sample()}`,'dashboard'),
 cfo:()=>wrap(`<div class="dash-label">CASH SCENARIO / דולר · דוגמה</div><h4>יתרה בסוף 20 ימי עבודה</h4><span class="bigvalue" data-cfoval>$620</span><div class="row"><span>הזמנות ליום</span><b data-cfoorders>3</b></div><input type="range" data-input="cfo" min="1" max="10" value="3" aria-label="הזמנות ליום בסימולציה">${note('500 פתיחה + הזמנות × 20 ימים × 12 תרומה − 600 הוצאות. מתעלם ממועדי זיכוי; לא תחזית.')}`,'dashboard'),
 inventory:()=>wrap(`<div class="dash-label">STOCK COVERAGE / נתוני דוגמה</div><div class="metric-grid"><div><small>מלאי דוגמה</small><b>100</b></div><div><small>ימי כיסוי</small><b data-stockdays>33.3</b></div></div><div class="row" style="margin-top:14px"><span>צריכת יחידות ליום</span><b data-demand>3</b></div><input type="range" data-input="inventory" min="1" max="12" value="3" aria-label="צריכה יומית בסימולציית מלאי"><div class="pill" data-stockrisk>מעל חלון אספקה וביטחון של 21 יום</div>${sample()}`,'dashboard'),
 seo:()=>wrap(`<div class="dash-label">SEARCH PREVIEW / לא תוצאת גוגל אמיתית</div><small dir="ltr">example.com › hair</small><h4 style="color:#355ca4;margin:10px 0" data-seotitle>NovaHair | ערכת צביעה ביתית</h4><p data-seodesc>מידע על המוצר, אפשרויות הבחירה ותכולת הערכה.</p><div class="pill">Product · Offer · Breadcrumb</div>${btn('גרסת תוכן נוספת','seo','','class="full" style="margin-top:15px"')}${note('לא מבטיח תוצאה עשירה, כוכבים או דירוג')}`)
};
let selection=new Set();try{const stored=JSON.parse(localStorage.getItem('tbg.catalog.v1.selection')||'[]');if(Array.isArray(stored))selection=new Set(stored.filter(id=>features.some(f=>f.id===id)));}catch{}
let category='all',onlySelected=false,toastTimer;
function demo(f){return `<div class="demo" data-demo="${f.id}">${renders[f.id]()}</div>`;}
function render(){const q=$('#search').value.toLowerCase().trim(),p=$('#priority').value;const filtered=features.filter(f=>(category==='all'||f.cat===category)&&(p==='all'||f.p===p)&&(!onlySelected||selection.has(f.id))&&(`${f.title} ${f.desc} ${f.id} ${sources[f.src].name} ${categories[f.cat]}`).toLowerCase().includes(q));$('#grid').innerHTML=filtered.map(f=>`<article class="card ${selection.has(f.id)?'chosen':''}" id="feature-${f.id}" data-card="${f.id}"><div class="card-head"><span>${String(features.indexOf(f)+1).padStart(2,'0')} / ${f.id.toUpperCase()}</span><span class="tag ${f.p}">${labels[f.p]}</span></div><div class="stage" data-cat="${f.cat}">${demo(f)}</div><div class="card-body"><div class="card-title"><h3>${esc(f.title)}</h3><button class="save" data-save="${f.id}" aria-label="${selection.has(f.id)?'הסר':'הוסף'} ${esc(f.title)} לרשימה" aria-pressed="${selection.has(f.id)}">${selection.has(f.id)?'★':'☆'}</button></div><p>${esc(f.desc)}</p><div class="meta"><span>${esc(sources[f.src].name)}</span><span>דמו עצמאי</span></div><div class="card-actions"><button class="quiet" data-open="${f.id}">הגדלה, מקור ופרטי הטמעה ↗</button></div></div></article>`).join('');$('#resultCount').textContent=`${filtered.length} מתוך ${features.length} פיצ׳רים` ;$('#empty').hidden=filtered.length>0;updateSelection();}
function renderCategories(){$('#categories').innerHTML=Object.entries(categories).map(([id,t])=>`<button data-category="${id}" class="${id===category?'active':''}" aria-pressed="${id===category}">${t}<small>${id==='all'?features.length:features.filter(f=>f.cat===id).length}</small></button>`).join('');}
function updateSelection(){for(const e of $$('.selectedCount'))e.textContent=selection.size;$('#selectionBar').hidden=!selection.size;for(const e of $$('[data-save]')){const on=selection.has(e.dataset.save);e.setAttribute('aria-pressed',String(on));e.textContent=on?'★':'☆';const f=features.find(x=>x.id===e.dataset.save);e.setAttribute('aria-label',`${on?'הסר':'הוסף'} ${f.title} לרשימה`);}for(const e of $$('[data-card]'))e.classList.toggle('chosen',selection.has(e.dataset.card));try{localStorage.setItem('tbg.catalog.v1.selection',JSON.stringify([...selection]));}catch{}}
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('show');toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function openDetail(id){const f=features.find(x=>x.id===id);if(!f)return;const s=sources[f.src];$('#detailLabel').textContent=`${categories[f.cat]} / ${f.id.toUpperCase()}`;$('#detailContent').innerHTML=`<div class="detail-grid"><div><div class="detail-stage">${demo(f)}</div><div class="detail-notice">דמו אינטראקטיבי מקורי לקטלוג. אינו הקוד או העיצוב המדויק של ${esc(s.name)}. אינו מחובר לחנות.</div></div><div><span class="tag ${f.p}">${labels[f.p]}</span><h2 style="margin-top:10px">${esc(f.title)}</h2><p>${esc(f.desc)}</p><button class="save" data-save="${f.id}" aria-label="שמירה ברשימה" aria-pressed="${selection.has(id)}">${selection.has(id)?'★':'☆'}</button><span style="font-size:12px;margin-inline-start:8px">סימון להתלבטות — לא אישור הטמעה</span><div class="detail-fields"><div><b>מה אפשר לקבל מהמקור?</b><p>${esc(s.ready)}</p></div><div><b>מה צריך להשלים אצלנו?</b><p>${esc(f.needs)}</p></div><div><b>מה לבדוק לפני שמאמצים?</b><p>${esc(f.risk)}</p></div><div><b>איך נמדוד הצלחה?</b><p>${esc(f.metric)}</p></div></div><div class="detail-sources"><a class="source-link" href="${s.url}" target="_blank" rel="noopener noreferrer">מקור / ${esc(s.name)} ↗</a><br><a class="source-link" href="${s.demo}" target="_blank" rel="noopener noreferrer">הדמו או התיעוד המקוריים ↗</a><small>${esc(s.license)}</small></div></div></div>`;if(!$('#detail').open)$('#detail').showModal();$('#detail').scrollTop=0;updateSelection();}
function selectOption(b,selector='button'){const group=b.parentElement;for(const x of $$(selector,group)){x.classList.toggle('on',x===b);if(x.hasAttribute('aria-pressed'))x.setAttribute('aria-pressed',String(x===b));}}
document.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.classList.add('failed');e.target.alt='תמונת המקור לא נטענה; ההדגמה זמינה ללא התמונה';}},true);
document.addEventListener('click',e=>{
 const save=e.target.closest('[data-save]');if(save){const id=save.dataset.save;selection.has(id)?selection.delete(id):selection.add(id);updateSelection();if(onlySelected)render();return;}
 const cat=e.target.closest('[data-category]');if(cat){category=cat.dataset.category;renderCategories();render();return;}
 const open=e.target.closest('[data-open]');if(open){openDetail(open.dataset.open);return;}
 const b=e.target.closest('[data-action]');if(!b)return;const d=b.closest('[data-demo]');if(!d)return;const a=b.dataset.action,v=b.dataset.value;
 switch(a){
 case 'notify':toast(v);break;case 'checkout':toast('זהו סל הדגמה בלבד. אין מעבר לקופה ואין חיוב.');break;
 case 'qty':{const q=$('[data-q]',d);const n=Math.max(1,Math.min(6,Number(q.textContent)+Number(v)));q.textContent=n;$('[data-total]',d).textContent=money(n*129);break;}
 case 'bundle':selectOption(b);$('[data-bundleprice]',d).textContent=money(Number(v));break;
 case 'mix':{const parts=v.split(':'),row=b.closest('.qty'),q=$('[data-q]',row);const all=$$('[data-q]',d);const total=all.reduce((s,x)=>s+Number(x.textContent),0);const delta=Number(parts[1]);if(delta>0&&total>=3){toast('החבילה מלאה. יש להפחית יחידה לפני הוספת גוון אחר.');break;}q.textContent=Math.max(0,Number(q.textContent)+delta);const n=all.reduce((s,x)=>s+Number(x.textContent),0);$('[data-mixcount]',d).textContent=n+' / 3';$('[data-mixdone]',d).disabled=n!==3;$('[data-mixdone]',d).textContent=n===3?'ההרכב מוכן — דמו':`בחרי עוד ${3-n} יח׳`;break;}
 case 'mixdone':toast('ההרכב תקין בדמו. לפני חיבור לחנות יידרש מיפוי SKU ומלאי.');break;
 case 'shade':selectOption(b);if($('[data-shadelabel]',d))$('[data-shadelabel]',d).textContent=v;else toast('נבחר גוון '+v+' בהדגמה בלבד.');break;
 case 'gallery':selectOption(b);{const im=$('[data-galleryimg]',d);im.classList.remove('failed');im.src=assets[v];$('[data-gallerycaption]',d).textContent={pack:'מוצר / 01',hero:'מותג / 02',gloss:'גלוס / 03'}[v];}break;
 case 'video':$('[data-videostate]',d).textContent='נבחר: '+v+' · הדגמת נגן, ללא וידאו מקור';break;
 case 'review':selectOption(b);$('[data-review]',d).textContent='כאן תוצג ביקורת אמיתית ומאושרת בנושא '+v+'.';break;
 case 'delivery':$('[data-delivery]',d).hidden=!$('[data-delivery]',d).hidden;break;
 case 'quick':$('[data-quickclosed]',d).hidden=!$('[data-quickclosed]',d).hidden;$('[data-quickopen]',d).hidden=!$('[data-quickopen]',d).hidden;break;
 case 'choice':$('[data-choice]',d).textContent='נבחרה אפשרות הדגמה: '+v;break;
 case 'quiz':{const options=$('[data-quizoptions]',d);if(!d.dataset.step){d.dataset.step='2';d.dataset.answer=v;$('[data-quizstep]',d).textContent='שאלה 2 מתוך 2';$('[data-quiztitle]',d).textContent='מה תרצי לראות קודם?';options.innerHTML=['מדריך קצר','פרטי מוצר'].map(t=>btn(t,'quiz',t,'class="option"')).join('');}else{$('[data-quizstep]',d).textContent='סיום הדגמה';$('[data-quiztitle]',d).textContent='הצעד הבא: '+v;options.innerHTML=`<p>בתוצאה אמיתית יופיע מידע מאושר בנושא ${esc(d.dataset.answer)}. לא נקבע גוון ולא ניתנה המלצה רפואית.</p>${btn('להתחיל מחדש','quizreset')}`;}break;}
 case 'quizreset':d.innerHTML=renders.quiz();delete d.dataset.step;delete d.dataset.answer;break;
 case 'popupclose':$('.popup',d).hidden=true;$('[data-action=popupreset]',d).hidden=false;break;
 case 'popupreset':$('.popup',d).hidden=false;$('[data-action=popupreset]',d).hidden=true;break;
 case 'chat':$('[data-chat]',d).textContent={גוונים:'הגוון המדויק תלוי במוצר ובשיער. כאן יופיע מדריך בחירה מאושר.',משלוח:'כאן יופיעו סוג המסירה וטווח ההגעה מתוך נתוני המשלוח הפעילים.',שימוש:'יש לקרוא את ההוראות והאזהרות על האריזה המקורית.'}[v];break;
 case 'cls':{const im=$('[data-clsimg]',d),reserved=$('[data-input=clsreserve]',d).checked;if(reserved){im.hidden=false;im.style.visibility='visible';}else im.hidden=!im.hidden;break;}
 case 'scripts':{const optimized=d.dataset.optimized!=='yes';d.dataset.optimized=optimized?'yes':'no';$$('.scriptline i',d).forEach((x,i)=>{x.style.setProperty('--w',(optimized?[95,85,30,15]:[95,85,80,70])[i]+'%');x.style.marginInlineStart=optimized&&i>1?'45%':'0';});b.textContent=optimized?'איפוס סימולציה':'להדגים טעינה מדורגת';break;}
 case 'quality':$$('.checkrow em',d).forEach((x,i)=>{x.textContent=i===2?'נדרש QA ידני':'תקין — דוגמה';x.classList.toggle('warn',i===2);});toast('הוצג דוח סינתטי בלבד. לא הורצה בדיקה של החנות.');break;
 case 'node':for(const x of $$('.node',d))x.classList.toggle('selected',x===b);$('[data-nodetext]',d).textContent=v;break;
 case 'ab':selectOption(b);$('[data-abtitle]',d).textContent=v==='A'?'הצבע שלך, בבית.':'מה צריך לדעת לפני שבוחרים גוון?';$('[data-abcopy]',d).textContent=v==='A'?'הצעה ממוקדת מוצר.':'גרסה שמתחילה בשאלה ובהסבר.';break;
 case 'seo':{const second=d.dataset.second!=='yes';d.dataset.second=second?'yes':'no';$('[data-seotitle]',d).textContent=second?'איך בוחרים ערכת צביעה ביתית? | NovaHair':'NovaHair | ערכת צביעה ביתית';$('[data-seodesc]',d).textContent=second?'מדריך מסחרי: תכולה, גוונים, הוראות ומידע לפני קנייה.':'מידע על המוצר, אפשרויות הבחירה ותכולת הערכה.';break;}
 }
});
document.addEventListener('input',e=>{const t=e.target,d=t.closest('[data-demo]');if(!d||!t.dataset.input)return;const v=Number(t.value);switch(t.dataset.input){
 case 'shipping':$('[data-amount]',d).textContent=money(v);$('[data-fill]',d).style.setProperty('--w',Math.min(100,v/199*100)+'%');$('[data-shiptext]',d).textContent=v>=199?'הגעת לסף הדוגמה למשלוח חינם':`עוד ${money(199-v)} למשלוח חינם`;break;
 case 'bump':$('[data-bumptotal]',d).textContent=money(219+(t.checked?29:0));break;
 case 'beforeafter':$('.after',d).style.clipPath=`inset(0 ${100-v}% 0 0)`;$('.divider',d).style.left=v+'%';break;
 case 'imagespeed':$('[data-imgwidth]',d).textContent=v+'px';$('[data-imgkb]',d).textContent=Math.round(v*.3)+' KB';break;
 case 'videoload':$('[data-videobytes]',d).textContent=t.checked?'240 KB':'12 MB';$('[data-fill]',d).style.setProperty('--w',t.checked?'2%':'100%');break;
 case 'clsreserve':{const im=$('[data-clsimg]',d);im.hidden=!t.checked;im.style.visibility=t.checked?'hidden':'visible';break;}
 case 'funnel':{const nums=t.value==='social'?[1000,120,60,24]:[800,112,70,32];$$('.funnel-row b',d).forEach((x,i)=>x.textContent=nums[i]);break;}
 case 'cfo':$('[data-cfoorders]',d).textContent=v;$('[data-cfoval]',d).textContent='$'+new Intl.NumberFormat('en-US').format(500+v*20*12-600);break;
 case 'inventory':$('[data-demand]',d).textContent=v;$('[data-stockdays]',d).textContent=(100/v).toFixed(1);$('[data-stockrisk]',d).textContent=100/v<21?'מתחת לחלון 21 יום — סיכון בדוגמה':'מעל חלון אספקה וביטחון של 21 יום';break;
}});
document.addEventListener('submit',e=>{if(e.target.matches('[data-demoform]')){e.preventDefault();e.target.reset();toast('הטופס תקין בדמו. שום כתובת לא נשמרה או נשלחה.');}});
$('#search').addEventListener('input',render);$('#priority').addEventListener('change',render);
function toggleSelected(force){onlySelected=typeof force==='boolean'?force:!onlySelected;$('#onlySelected').setAttribute('aria-pressed',String(onlySelected));render();}
$('#onlySelected').onclick=()=>toggleSelected();$('#showSelected').onclick=()=>{toggleSelected(true);$('#catalog').scrollIntoView();};
$('#reset').onclick=()=>{category='all';$('#search').value='';$('#priority').value='all';onlySelected=false;$('#onlySelected').setAttribute('aria-pressed','false');renderCategories();render();};
$('#clear').onclick=()=>{if(!window.confirm('לנקות את רשימת הבחירות מהמכשיר הזה?'))return;selection.clear();updateSelection();if(onlySelected)render();};
$('#closeDialog').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
function brief(){return '# TBG Commerce Atlas — רשימת בחירות\n\nסימון להתלבטות בלבד; לא אישור שינוי בחנות.\nהדמואים עצמאיים ואינם רכיבי production או צילום מהמקור.\n\n'+features.filter(f=>selection.has(f.id)).map((f,i)=>`${i+1}. ${f.title} [${f.id}]\n   מקור: ${sources[f.src].url}\n   מה להשלים: ${f.needs}\n   זהירות: ${f.risk}\n   מדד: ${f.metric}`).join('\n\n')+'\n\nלפני פיתוח: לבדוק קוד קיים, רישיון וגרסה; לעבוד ב-staging; לא לשנות production בלי אישור מפורש.\n';}
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([brief()],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='tbg-feature-shortlist.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);};
$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(brief());toast('רשימת הבחירות הועתקה. אפשר להעביר אותה לאייג׳נט.');}catch{toast('הדפדפן חסם העתקה. השתמש בכפתור הורדת הרשימה.');}};
$('#featureCount').textContent=features.length;renderCategories();render();
})();
